### ISSUE TITLE
Existing Projects Dropdown is time consuming

### ISSUE THREAD

**Issue by arcanefoam** [epsilonlabs/emc-artisan#10]
It is possible to get the existing projects list and show it in a drop down. However, getting all the projects consumes time. Currently the configuration dialog will block until the information is retrieved. An alternative is to run this on the background, and enable the dropdown as soon as we get the results.

**Comment by kolovos** [comment]
Another alternative would be to use a text box (in case users prefer to type in the name of the project) and a browse button

**Comment by arcanefoam** [comment]
Went for Dimitris' option using the provided OpenFileDialog. The other option, whilst possible, get very tricky as UI synchronisation requires use of threads and Jawin gets harder if using multiple threads.
