### ISSUE TITLE
Merge org.eclipse.epsilon.emc.ptcim and org.eclipse.epsilon.emc.ptcim.jawin

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emc-artisan#20]
Since the OLE abstraction layer no longer exists, the two plugins can be merged under org.eclipse.epsilon.emc.ptcim. Jawin*-named classes could be also renamed to Ptcim* for consistency

**Comment by zolotas4** [comment]
Closed (dec4351403cf9dab4ecdc1c267acfb1266b3b68e and 820ea63c440e13989c88fb9e72c6b20a2ca20a60)
