### ISSUE TITLE
Property normalisation is not working

### ISSUE THREAD

**Issue by zolotas4** [epsilonlabs/emc-artisan#26]
In the last version property normalisation is not working. For attributes/references you need to pass the name without spaces (e.g., `ScopingItem`) otherwise it throws an exception. In contrast, for types you need to pass it using a space (e.g., `Data Store`).

**Comment by arcanefoam** [comment]
From a quick review by Thanos it seems that the normalisation method is just not being invoked. So it might be as simple as making sure the method is invoked when necessary. 

Need to add a JUnit test for the normalisation so in the future code refactoring does not break this.

**Comment by beatrizsanchez** [comment]
I think it should be closed with 75946bfbae4ee0bf55890934eb61a9ba27e335d8 . See tests

**Comment by beatrizsanchez** [comment]
I believe this time it should be fixed for properties (b41245d22d6e663df6dd65cc9952a30e91dce95c)
