### ISSUE TITLE
Rename artisan to ptcim everywhere

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emc-artisan#4]
Given that Artisan Studio is now PTC Integrity Modeller and it's unlikely that it will change back to its previous name, we should eliminate all references to "artisan" and replace them with "ptcim" instead e.g. the org.eclipse.epsilon.emc.artisan plugin should become org.eclipse.epsilon.emc.ptcim, ArtisanModel should become PtcimModel etc. The name of the repo should also be changed eventually to "emc-ptcim"

**Comment by arcanefoam** [comment]
Fixed
