### ISSUE TITLE
Inconsistent plugin/package name

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emc-artisan#5]
The root package of the org.eclipse.epsilon.emc.artisan.COM plugin is org.eclipse.epsilon.emc.COM - which is unusual as these typically match in Eclipse plugins. On a related note, I'd suggest changing "COM" to "com" in package/plugin names.

**Comment by arcanefoam** [comment]
Agree, further, I am changing it to OLE, as it seems that is the actual type of bridge we are using.

**Comment by arcanefoam** [comment]
Fixed
