### ISSUE TITLE
Navigation from the validation view to the PTC IM should happen in a background job

### ISSUE THREAD

**Issue by kolovos** [epsilonlabs/emc-artisan#6]
When PTC IM isn't started, double-clicking on a failed constraint in the validation view makes Eclipse freeze for quite a while until PTC IM launches. Ideally this should be done in a background job. See http://www.vogella.com/tutorials/EclipseJobs/article.html#eclipse-jobs-api

**Comment by kolovos** [comment]
Actually, it may make more sense to do this at the extension point level as other implementations may have the same problem in the future

**Comment by arcanefoam** [comment]
Agree.  Will look into this.
